# Name of your application. Used to uniquely configure containers.
service: eml2html

# Name of the container image.
image: mconnell/eml2html

# Deploy to these servers.
servers:
  web:
    - <%= ENV["EML_2_HTML_IP_ADDRESS"] %>

proxy:
  ssl: true
  host: eml2html.com

# Credentials for your image host.
registry:
  server: localhost:5555

# Configure builder setup.
builder:
  arch: amd64
